### ISSUE TITLE
Additional field values are not parsing from form data

### ISSUE THREAD

**Issue by Biaggio74** [dstpierre/react-trix#21]
I am trying to send additional form data through the `uploadData` props. From the code it seems to be that these object should go to each form fields, correct?

`        uploadData={{
          "fileName": "test_file",
          "projectId": "PRID123",
          "userEmail": "bela@bela.com",
        }}`

Then I am using busboy to parse the multipart-data with NodeJS as follows:

```javascript
    //This code will process each non-file field in the form.
    busboy.on('field', (fieldname, val) => {
      //TODO(developer): Process submitted field values here
      console.log(`Processed field ${fieldname}: ${val}.`);
      fields[fieldname]= val;
    });
```

However, only the first field name returns in the code
`>  Processed field Content-Type: application/pdf.`

which is ok, but not the others I have just passed. I was expecting to happen those from the following source code:

```javascript
  private uploadAttachment(attachment: any) {
    var file, form, xhr;
    file = attachment.file;
    form = new FormData();
    // add any custom data that were passed
    if (this.props.uploadData) {
      for (var k in this.props.uploadData) {
        form[k] = this.props.uploadData[k];
      }
    }
    form.append("Content-Type", file.type);
    form.append("file", file);
    xhr = new XMLHttpRequest();
    xhr.open("POST", this.props.uploadURL, true);
    xhr.upload.onprogress = (event) => {
      var progress = event.loaded / event.total * 100;
      return attachment.setUploadProgress(progress);
    };
```

**Comment by dstpierre** [comment]
@Biaggio74 thank you for reporting the issue. It's fixed in `0.5.1` which should be available on NPM now.
